services:
  instagram_nextjs:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
